name: comt-tools
channels:
  - conda-forge
  - defaults
dependencies:
  - netcdf4=1.5.3
  - numpy=1.19.5
  - pandas=1.2.0
  - xarray=0.16.2
  - cartopy=0.18.0
  - wrf-python=1.3.2
  - geographiclib=1.50
  - erddapy=0.9.0
  - pickle5=0.0.11
  - scipy=1.6.0